version: "3"
services:
  postgres:
    container_name: azdev_pg
    image: agilelabs/azdev-apollo-example:main
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=azdev-example
      - POSTGRES_PASSWORD=password
      - PGDATA=pgdata
